//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDemoData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentDetail
    {
        public string DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> TotalEmployee { get; set; }
        public string EmployeeID { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
